### ISSUE TITLE
extern.ExternCalledProcessError

### ISSUE THREAD

**Issue by zhanwen-cheng** [wwood/singlem_extra_packages#1]
Hi wwood, I was running singlem with extra_packages to check the 16s reads in my fastq file. The reads I used was donwloaded from ENA(ERR599383) http://ftp.sra.ebi.ac.uk/vol1/err/ERR599/ERR599383. As it was not sopported for pair-ends reads in singlem_extra_packages, so I cat the two fastq file into a single fastq file(ERR599383.fastq). The command I used was like this: `singlem pipe --singlem_packages ~/data/data_base/singlem_extra_packages/release1/4.40.2013_08_greengenes_97_otus.with_euks.spkg --sequences ERR599383.fastq --otu_table 16s_table.csv`. However, it repored error while runing to HMM
`11/05/2020 03:27:40 PM INFO: Loaded 1 SingleM packages
11/05/2020 03:27:40 PM INFO: Using as input 1 different sequence files e.g. ERR599383.fastq
11/05/2020 03:27:40 PM INFO: Searching with 1 SingleM package(s)
11/05/2020 03:27:40 PM INFO: Searching for reads matching 1 different nucleotide HMM(s)
Traceback (most recent call last):
  File "/home/chengzw/anaconda3/envs/singlem/bin/singlem", line 513, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 176, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 868, in _search
    run(hmms, graftm_nucleotide_search_directory, False)
  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 848, in run
    extern.run(cmd)
  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide   --filter_minimum 95 --threads 1 --forward ERR599383.fastq --search_only --search_hmm_files /home/chengzw/data/data_base/singlem_extra_packages/release1/4.40.2013_08_greengenes_97_otus.with_euks.spkg/4.40.2013_08_greengenes_97_otus.with_euks/graftm6wK98G_search.hmm --output_directory /dev/shm/tmpuq0j6xjk/graftm_nucleotide_search --aln_hmm_file /home/chengzw/data/data_base/singlem_extra_packages/release1/4.40.2013_08_greengenes_97_otus.with_euks.spkg/4.40.2013_08_greengenes_97_otus.with_euks/graftm6wK98G_search.hmm  returned non-zero exit status 1.
STDERR was: b'Traceback (most recent call last):\n  File "/home/chengzw/anaconda3/envs/singlem/bin/graftM", line 415, in <module>\n    Run(args).main()\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 613, in main\n    self.graft()\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 409, in graft\n    self.args.evalue\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/graftm/timeit.py", line 10, in timed\n    result = method(*args, **kw)\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 1038, in nt_db_search\n    hit_reads_fasta)\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 1112, in search_and_extract_nucleotides_matching_nucleotide_database\n    hits\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 534, in _extract_from_raw_reads\n    extern.run(extract_cmd, stdin=\'\\n\'.join(input_reads))\n  File "/home/chengzw/anaconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run\n    raise ExternCalledProcessError(process, command)\nextern.ExternCalledProcessError: Command mfqe --output-uncompressed --fasta-read-name-lists /dev/stdin --input-fasta <(awk \'{print ">" substr($0,2);getline;print;getline;getline}\' \'ERR599383.fastq\') --output-fasta-files \'/dev/shm/tmpuq0j6xjk/tempfiles/_raw_extracted_reads.fa1p7pxhh2\' returned non-zero exit status 101.\nSTDERR was: b"[2020-11-05T07:43:12Z INFO  mfqe] Read in 2534 read names from /dev/stdin\\n[2020-11-05T07:43:12Z INFO  mfqe] Iterating input FASTQ file\\n[2020-11-05T07:43:56Z INFO  mfqe] Extracted 5068 reads from 26892968 total\\nthread \'main\' panicked at \'Mismatching numbers of read names were observed. Expected:\\n[2534]\\nbut found\\n[5068]\', src/main.rs:333:9\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n"STDOUT was: b\'\'\n'STDOUT was: b''`.
Could you help me with that? Should I cat the fastq file toghther if I wanted to check 16s in my sample? Or should I run the commad with ERR599383_1.fastq and ERR599383_2.fastq repectively?

**Comment by wwood** [comment]
Hi,

Yes unfortunately singlem cannot handle paired read input on a nucleotide package, haven't gotten around to implementing that. You can't concatenate them because then multiple sequences have the same name (before the space) on your seuqencing set, it seems.

You could workaround by either just running the forward reads, or running forward and reverse separately i.e. giving your forward reads to the `--forward` flag, and then giving the reverse reads to the `--forward` flag in a second run of singlem

**Comment by zhanwen-cheng** [comment]
OK, thanks a lot!
